apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: pelasne-api-identity
spec:
  type: 0
  ResourceID: /subscriptions/8e95e0bb-d7cc-4454-9443-75ca862d34c1/resourceGroups/pelasne-identities/providers/Microsoft.ManagedIdentity/userAssignedIdentities/pelasne-api-identity
  ClientID: 451b2d9d-ba49-4596-a481-4281f031bb3d
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: pelasne-api-identity-binding
spec:
  AzureIdentity: pelasne-api-identity
  Selector: pelasne-api-identity-binding
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    aadpodidbinding: pelasne-api-identity-binding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        aadpodidbinding: pelasne-api-identity-binding
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: api
        image: pelasneregistry.azurecr.io/api:1.0.4
        env:
        - name: LOG_LEVEL
          value: "Debug"
        - name: HOST_URL
          value: "http://*:80"
        - name: APPCONFIG
          value: "pelasne-config"
        - name: CONFIG_KEYS
          value: "sample:api:dev:*, sample:common:dev:*"
        - name: PRESENT_CONFIG_WEB
          value: "sample:web:dev:*"
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          periodSeconds: 3
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 80
  selector:
    app: api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - secretName: ssl-full
  rules:
  - host: api.plasne.com
    http:
      paths:
      - backend:
          serviceName: api
          servicePort: 80